
    create table collection_box (
        id bigint generated by default as identity,
        primary key (id)
    );

    create table fundraising_event (
        box_id bigint unique,
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table stored_money (
        amount numeric(38,2),
        currency tinyint check (currency between 0 and 2),
        box_id bigint,
        id bigint generated by default as identity,
        primary key (id)
    );

    alter table if exists fundraising_event 
       add constraint FKbv6h8i9t1rtcemrt05wtr7i7e 
       foreign key (box_id) 
       references collection_box;

    alter table if exists stored_money 
       add constraint FK7wyfkv87p88q9st2e4vu3ox44 
       foreign key (box_id) 
       references collection_box;

    create table collection_box (
        id bigint generated by default as identity,
        primary key (id)
    );

    create table fundraising_event (
        box_id bigint unique,
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table stored_money (
        amount numeric(38,2),
        currency tinyint check (currency between 0 and 2),
        box_id bigint,
        id bigint generated by default as identity,
        primary key (id)
    );

    alter table if exists fundraising_event 
       add constraint FKbv6h8i9t1rtcemrt05wtr7i7e 
       foreign key (box_id) 
       references collection_box;

    alter table if exists stored_money 
       add constraint FK7wyfkv87p88q9st2e4vu3ox44 
       foreign key (box_id) 
       references collection_box;
